// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEc1mvc1blgdN8MBxz4h3BhWdvcAgbAY4',
    appId: '1:303969148042:web:3b0119f8cdb875199f6173',
    messagingSenderId: '303969148042',
    projectId: 'metroswap-78daf',
    authDomain: 'metroswap-78daf.firebaseapp.com',
    storageBucket: 'metroswap-78daf.firebasestorage.app',
    measurementId: 'G-2XT5RTDE8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJ9aPSrzpxvi4O-ggLCymxNFrudGyB6s',
    appId: '1:303969148042:android:d9b0569d4e2ff1e99f6173',
    messagingSenderId: '303969148042',
    projectId: 'metroswap-78daf',
    storageBucket: 'metroswap-78daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwA_6mENdEbJ0ViqocrlBZw7Iz7pOSlmE',
    appId: '1:303969148042:ios:c436fed00a9d09c89f6173',
    messagingSenderId: '303969148042',
    projectId: 'metroswap-78daf',
    storageBucket: 'metroswap-78daf.firebasestorage.app',
    iosBundleId: 'com.example.metroswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwA_6mENdEbJ0ViqocrlBZw7Iz7pOSlmE',
    appId: '1:303969148042:ios:c436fed00a9d09c89f6173',
    messagingSenderId: '303969148042',
    projectId: 'metroswap-78daf',
    storageBucket: 'metroswap-78daf.firebasestorage.app',
    iosBundleId: 'com.example.metroswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEc1mvc1blgdN8MBxz4h3BhWdvcAgbAY4',
    appId: '1:303969148042:web:96bbc1f35ef59c1a9f6173',
    messagingSenderId: '303969148042',
    projectId: 'metroswap-78daf',
    authDomain: 'metroswap-78daf.firebaseapp.com',
    storageBucket: 'metroswap-78daf.firebasestorage.app',
    measurementId: 'G-RKFJB1S66G',
  );
}
